const companiesMock = [
  {
    id: 1,
    nome: "Alfa Solutions LTDA",
    categoria: "cliente recorrente",
    responsavel: "Marcos Vinícius",
    email: "marcos@alfasolutions.com",
    telefone: "(35) 99821-3344",
  },
  {
    id: 2,
    nome: "BR Logística",
    categoria: "em potencial",
    responsavel: "Renata Oliveira",
    email: "renata@brlogistica.com",
    telefone: "(11) 98745-1023",
  },
  {
    id: 3,
    nome: "Nova Era Engenharia",
    categoria: "não qualificado",
    responsavel: "Carlos Eduardo",
    email: "carlos@novaeraeng.com",
    telefone: "(31) 99654-7788",
  },
  {
    id: 4,
    nome: "Sul Minas Alimentos",
    categoria: "recompra",
    responsavel: "Fernanda Lopes",
    email: "fernanda@sulminasalimentos.com",
    telefone: "(35) 99112-4456",
  },
  {
    id: 5,
    nome: "TechWay Sistemas",
    categoria: "cliente recorrente",
    responsavel: "Lucas Andrade",
    email: "lucas@techway.com",
    telefone: "(19) 99773-8899",
  },
  {
    id: 6,
    nome: "Horizonte Consultoria",
    categoria: "em potencial",
    responsavel: "Patrícia Menezes",
    email: "patricia@horizonteconsultoria.com",
    telefone: "(21) 98834-5567",
  },
  {
    id: 7,
    nome: "Atlas Construções",
    categoria: "não qualificado",
    responsavel: "Rafael Pacheco",
    email: "rafael@atlasconstrucoes.com",
    telefone: "(27) 99567-2210",
  },
  {
    id: 8,
    nome: "Vértice Distribuidora",
    categoria: "recompra",
    responsavel: "Juliana Costa",
    email: "juliana@verticedist.com",
    telefone: "(48) 99210-9087",
  },
  {
    id: 9,
    nome: "PrimeTech Automação",
    categoria: "em potencial",
    responsavel: "Eduardo Farias",
    email: "eduardo@primetech.com",
    telefone: "(41) 99834-1122",
  },
  {
    id: 10,
    nome: "Vale Verde Sustentável",
    categoria: "cliente recorrente",
    responsavel: "Camila Rocha",
    email: "camila@valeverde.com",
    telefone: "(31) 99120-7789",
  },
  {
    id: 11,
    nome: "Orion Marketing Digital",
    categoria: "não qualificado",
    responsavel: "Thiago Martins",
    email: "thiago@orionmarketing.com",
    telefone: "(11) 98765-4432",
  },
  {
    id: 12,
    nome: "NorteSul Transportes",
    categoria: "recompra",
    responsavel: "Julio Cesar Almeida",
    email: "julio@nortesultransp.com",
    telefone: "(62) 99654-3301",
  },
]

export default companiesMock
